=== ArleneYuZhiwei/Pun-Generation/sem17_task7/trial/puns.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT corpus (text+)>
<!ATTLIST corpus lang CDATA #REQUIRED>
<!ATTLIST corpus id ID #REQUIRED>

<!ELEMENT text (word+)>
<!ATTLIST text id ID #REQUIRED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word id ID #REQUIRED>
<!ATTLIST word senses (1|2) "1">

=== ArleneYuZhiwei/Pun-Generation/sem17_task7/trial/subtask1-homographic-trial.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE corpus SYSTEM 'puns.dtd'>
<corpus lang="en" id="subtask1-homographic">
  <text id="t_1">
    <word id="t_1_0">I</word>
    <word id="t_1_1">used</word>
    <word id="t_1_2">to</word>
    <word id="t_1_3">be</word>
    <word id="t_1_4">a</word>
    <word id="t_1_5">banker</word>
    <word id="t_1_6">but</word>
    <word id="t_1_7">I</word>
    <word id="t_1_8">lost</word>
    <word id="t_1_9">interest</word>
    <word id="t_1_10">.</word>
  </text>
  <text id="t_2">
    <word id="t_2_0">This</word>
    <word id="t_2_1">sentence</word>
    <word id="t_2_2">contains</word>
    <word id="t_2_3">no</word>
    <word id="t_2_4">pun</word>
    <word id="t_2_5">.</word>
  </text>
  <text id="t_3">
    <word id="t_3_0">"</word>
    <word id="t_3_1">Quick</word>
    <word id="t_3_2">,</word>
    <word id="t_3_3">dive</word>
    <word id="t_3_4">into</word>
    <word id="t_3_5">those</word>
    <word id="t_3_6">reeds</word>
    <word id="t_3_7">!</word>
    <word id="t_3_8">"</word>
    <word id="t_3_9">Tom</word>
    <word id="t_3_10">rushed</word>
    <word id="t_3_11">.</word>
  </text>
</corpus>

=== ArleneYuZhiwei/Pun-Generation/sem17_task7/trial/subtask3-homographic-trial.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE corpus SYSTEM 'puns.dtd'>
<corpus lang="en" id="subtask3-homographic">
  <text id="t_1">
    <word id="t_1_0" senses="1">I</word>
    <word id="t_1_1" senses="1">used</word>
    <word id="t_1_2" senses="1">to</word>
    <word id="t_1_3" senses="1">be</word>
    <word id="t_1_4" senses="1">a</word>
    <word id="t_1_5" senses="1">banker</word>
    <word id="t_1_6" senses="1">but</word>
    <word id="t_1_7" senses="1">I</word>
    <word id="t_1_8" senses="1">lost</word>
    <word id="t_1_9" senses="2">interest</word>
    <word id="t_1_10" senses="1">.</word>
  </text>
  <text id="t_3">
    <word id="t_3_0" senses="1">"</word>
    <word id="t_3_1" senses="1">Quick</word>
    <word id="t_3_2" senses="1">,</word>
    <word id="t_3_3" senses="1">dive</word>
    <word id="t_3_4" senses="1">into</word>
    <word id="t_3_5" senses="1">those</word>
    <word id="t_3_6" senses="1">reeds</word>
    <word id="t_3_7" senses="1">!</word>
    <word id="t_3_8" senses="1">"</word>
    <word id="t_3_9" senses="1">Tom</word>
    <word id="t_3_10" senses="2">rushed</word>
    <word id="t_3_11" senses="1">.</word>
  </text>
</corpus>

=== ArleneYuZhiwei/Pun-Generation/sem17_task7/trial/subtask1-heterographic-trial.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE corpus SYSTEM 'puns.dtd'>
<corpus lang="en" id="subtask1-heterographic">
  <text id="t_1">
    <word id="t_1_0">When</word>
    <word id="t_1_1">the</word>
    <word id="t_1_2">church</word>
    <word id="t_1_3">bought</word>
    <word id="t_1_4">gas</word>
    <word id="t_1_5">for</word>
    <word id="t_1_6">their</word>
    <word id="t_1_7">annual</word>
    <word id="t_1_8">barbecue</word>
    <word id="t_1_9">,</word>
    <word id="t_1_10">proceeds</word>
    <word id="t_1_11">went</word>
    <word id="t_1_12">from</word>
    <word id="t_1_13">the</word>
    <word id="t_1_14">sacred</word>
    <word id="t_1_15">to</word>
    <word id="t_1_16">the</word>
    <word id="t_1_17">propane</word>
    <word id="t_1_18">.</word>
  </text>
  <text id="t_2">
    <word id="t_2_0">This</word>
    <word id="t_2_1">sentence</word>
    <word id="t_2_2">contains</word>
    <word id="t_2_3">no</word>
    <word id="t_2_4">pun</word>
    <word id="t_2_5">.</word>
  </text>
  <text id="t_3">
    <word id="t_3_0">"</word>
    <word id="t_3_1">I</word>
    <word id="t_3_2">ate</word>
    <word id="t_3_3">no</word>
    <word id="t_3_4">soap</word>
    <word id="t_3_5">,</word>
    <word id="t_3_6">"</word>
    <word id="t_3_7">Tom</word>
    <word id="t_3_8">lied</word>
    <word id="t_3_9">.</word>
  </text>
</corpus>

=== ArleneYuZhiwei/Pun-Generation/sem17_task7/trial/subtask3-heterographic-trial.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE corpus SYSTEM 'puns.dtd'>
<corpus lang="en" id="subtask3-heterographic">
  <text id="t_1">
    <word id="t_1_0" senses="1">When</word>
    <word id="t_1_1" senses="1">the</word>
    <word id="t_1_2" senses="1">church</word>
    <word id="t_1_3" senses="1">bought</word>
    <word id="t_1_4" senses="1">gas</word>
    <word id="t_1_5" senses="1">for</word>
    <word id="t_1_6" senses="1">their</word>
    <word id="t_1_7" senses="1">annual</word>
    <word id="t_1_8" senses="1">barbecue</word>
    <word id="t_1_9" senses="1">,</word>
    <word id="t_1_10" senses="1">proceeds</word>
    <word id="t_1_11" senses="1">went</word>
    <word id="t_1_12" senses="1">from</word>
    <word id="t_1_13" senses="1">the</word>
    <word id="t_1_14" senses="1">sacred</word>
    <word id="t_1_15" senses="1">to</word>
    <word id="t_1_16" senses="1">the</word>
    <word id="t_1_17" senses="2">propane</word>
    <word id="t_1_18" senses="1">.</word>
  </text>
  <text id="t_3">
    <word id="t_3_0" senses="1">"</word>
    <word id="t_3_1" senses="1">I</word>
    <word id="t_3_2" senses="1">ate</word>
    <word id="t_3_3" senses="1">no</word>
    <word id="t_3_4" senses="1">soap</word>
    <word id="t_3_5" senses="1">,</word>
    <word id="t_3_6" senses="1">"</word>
    <word id="t_3_7" senses="1">Tom</word>
    <word id="t_3_8" senses="2">lied</word>
    <word id="t_3_9" senses="1">.</word>
  </text>
</corpus>
